
name: Python Delete Pictures File

on:
  push:
    paths:
    - 'test_delete.py'
    - 'test_delete3.py'
    - 'requirements.txt'
    - '.github/workflows/pythonapp.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # we should give github deside own speed max-parallel: 1
      matrix:
        python: [3.8, 3.9, 3.10.10, 3.11 ]
        #depricated versions 3.6, 3.7
        #We are moving to 3.6 -> versions should work on 3.5 version, also  currently broken no 64Arch [3.12]
        os: [ubuntu-latest] # we dont need windows currently, but is works currently [ windows-2019]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: ${{ matrix.python }}
    - name: Codecov
      uses: codecov/codecov-action@v3.1.4
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Test test_delete.py with pytest
      run: |
        pip3 install pytest
        python3 -m pytest test_delete.py
    - name: Test test_delete3.py with pytest and add report
      run: |
        pip3 install pytest pytest-cov
        python3 -m pytest  --cov=./ --cov-report=xml test_delete3.py
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
