
name: Python Delete Pictures File

on:
  push:
    paths:
    - 'test_delete.py'
    - 'requirements.txt'
    - '.github/workflows/pythonapp.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8, 3.9, 3.10.0]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Test with pytest
      run: |
        pip3 install pytest
        python3 -m pytest test_delete.py
