
name: Python Delete Pictures File

on:
  push:
    paths:
    - 'test_delete.py'
    - 'test_delete2.py'
    - 'test_delete3.py'
    - 'requirements.txt'
    - '.github/workflows/pythonapp.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # we should give github deside own speed max-parallel: 1
      matrix:
        python: [3.9, 3.10.10, 3.11, 3.12]
        #depricated versions 3.6, 3.7 and 3.8 in 18.10.2024
        #We are moving to 3.6 -> versions should work on 3.5 version, also  currently broken no 64Arch [3.12]
        os: [ubuntu-latest] # we dont need windows currently, but is works currently [ windows-2019]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pytest pytest-cov
#    - name: Test test_delete.py with pytest
#      run: |
#        python3 -m pytest test_delete.py
#    - name: Test test_delete2.py with pytest
#      run: |
#        python3 -m pytest test_delete2.py
    - name: Test test_delete3.py with pytest and add report
      run: |
        python3 -m pytest test_delete3.py

