
name: Python Delete Pictures File

on:
  push:
    paths:
    - 'test_delete.py'
    - 'test_delete3.py'
    - 'requirements.txt'
    - '.github/workflows/pythonapp.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        python: [3.5, 3.6, 3.7, 3.8, 3.9, 3.9.15, 3.10.0, 3.10.8, 3.11, 3.12]
        os: [ubuntu-latest, windows-2019]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Test with pytest
      run: |
        pip3 install pytest
        python3 -m pytest test_delete.py
