name: Python Delete Pictures File

#on: [push]
on: workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.5.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.5.7
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Test with pytest
      run: |
        pip3 install pytest
        python3 -m pytest Delete.py

